### ISSUE TITLE
Playwright MCP latest version (0.0.47) is not working with Node.js, but it is working with mcp version: 0.0.46

### ISSUE THREAD

**Issue by dkundu56** [microsoft/playwright-mcp#1200]
`node:internal/modules/cjs/loader:1408
  throw err;
  ^

Error: Cannot find module './utilsBundleImpl'
Require stack:
- /Users/dkundu/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/utilsBundle.js
- /Users/dkundu/.npm/_npx/9833c18b2d85bc59/node_modules/@playwright/mcp/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1405:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1061:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1066:22)
    at Module._load (node:internal/modules/cjs/loader:1215:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1491:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/dkundu/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/utilsBundle.js:46:16)
    at Module._compile (node:internal/modules/cjs/loader:1734:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dkundu/.npm/_npx/9833c18b2d85bc59/node_modules/playwright-core/lib/utilsBundle.js',
    '/Users/dkundu/.npm/_npx/9833c18b2d85bc59/node_modules/@playwright/mcp/cli.js'
  ]
}

Node.js v24.1.0
  + Exception Group Traceback (most recent call last):
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/src/workflows/uc_graph_workflow.py", line 142, in <module>
  |     asyncio.run(uc_graph_runner(target_website, username, password))
  |     ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 195, in run
  |     return runner.run(main)
  |            ~~~~~~~~~~^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
  |     return future.result()
  |            ~~~~~~~~~~~~~^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/src/workflows/uc_graph_workflow.py", line 127, in uc_graph_runner
  |     final_state = await app.ainvoke(initial_state)
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/pregel/main.py", line 3171, in ainvoke
  |     async for chunk in self.astream(
  |     ...<29 lines>...
  |             chunks.append(chunk)
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/pregel/main.py", line 2993, in astream
  |     async for _ in runner.atick(
  |     ...<13 lines>...
  |             yield o
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/pregel/_runner.py", line 295, in atick
  |     await arun_with_retry(
  |     ...<15 lines>...
  |     )
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/pregel/_retry.py", line 137, in arun_with_retry
  |     return await task.proc.ainvoke(task.input, config)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/_internal/_runnable.py", line 706, in ainvoke
  |     input = await asyncio.create_task(
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |         step.ainvoke(input, config, **kwargs), context=context
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     )
  |     ^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langgraph/_internal/_runnable.py", line 474, in ainvoke
  |     ret = await self.afunc(*args, **kwargs)
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/src/workflows/uc_graph_workflow.py", line 42, in explorer_node
  |     result = await activity_explorer_agent_langGraph(
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |         target_website, playwright_report_dir, agent_report_dir
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |     )
  |     ^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/src/agents/langGraph/activity_explorer_agents_langGraph.py", line 25, in activity_explorer_agent_langGraph
  |     async with playwright_mcp_client_isolated.session("playwright") as session:
  |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 214, in __aenter__
  |     return await anext(self.gen)
  |            ^^^^^^^^^^^^^^^^^^^^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/client.py", line 123, in session
  |     async with create_session(self.connections[server_name]) as session:
  |                ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 235, in __aexit__
  |     await self.gen.athrow(value)
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/sessions.py", line 403, in create_session
  |     async with _create_stdio_session(**params) as session:
  |                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 235, in __aexit__
  |     await self.gen.athrow(value)
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/sessions.py", line 229, in _create_stdio_session
  |     stdio_client(server_params) as (read, write),
  |     ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/python@3.13/3.13.3_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/contextlib.py", line 235, in __aexit__
  |     await self.gen.athrow(value)
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/mcp/client/stdio/__init__.py", line 183, in stdio_client
  |     anyio.create_task_group() as tg,
  |     ~~~~~~~~~~~~~~~~~~~~~~~^^
  |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 781, in __aexit__
  |     raise BaseExceptionGroup(
  |         "unhandled errors in a TaskGroup", self._exceptions
  |     ) from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  | During task with name 'explorer' and id '6a1e9c9e-aebf-d0d0-b010-c4b12641fdaa'
  +-+---------------- 1 ----------------
    | Exception Group Traceback (most recent call last):
    |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/mcp/client/stdio/__init__.py", line 189, in stdio_client
    |     yield read_stream, write_stream
    |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/sessions.py", line 230, in _create_stdio_session
    |     ClientSession(read, write, **(session_kwargs or {})) as session,
    |     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/mcp/shared/session.py", line 218, in __aexit__
    |     return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 781, in __aexit__
    |     raise BaseExceptionGroup(
    |         "unhandled errors in a TaskGroup", self._exceptions
    |     ) from None
    | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    +-+---------------- 1 ----------------
      | Traceback (most recent call last):
      |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/sessions.py", line 232, in _create_stdio_session
      |     yield session
      |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/sessions.py", line 404, in create_session
      |     yield session
      |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/langchain_mcp_adapters/client.py", line 125, in session
❌Error running explorer agent: unhandled errors in a TaskGroup (1 sub-exception)

⏱️ Total execution time: 1.31 seconds
      |     await session.initialize()
      |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/mcp/client/session.py", line 152, in initialize
      |     result = await self.send_request(
      |              ^^^^^^^^^^^^^^^^^^^^^^^^
      |     ...<15 lines>...
      |     )
      |     ^
      |   File "/Users/dkundu/projects/Netskope_AI_Projects/Agentic_AI_Universal_Connector/.venv/lib/python3.13/site-packages/mcp/shared/session.py", line 286, in send_request
      |     raise McpError(response_or_error.error)
      | mcp.shared.exceptions.McpError: Connection closed`

**Comment by pavelfeldman** [comment]
Your `npx` cache is corrupt, search on how to fix it on the internet.
